apiVersion: v2
name: file-syncer
description: A Helm chart for file-syncer service
type: application
version: 2.1.4
appVersion: 2.1.4
dependencies:
  - name: mc-labels-and-annotations
    version: 0.7.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    alias: mcLabelsAndAnnotations
